

-------------------------------------------------------------------------
Systeminfo:
CPU:               AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
Number of CPUs:    16
RAM:               15.2GB
Diskinfo:          45.9GB/475.7GB
Operating system:  Windows-10-10.0.19045
Long path support: False
-------------------------------------------------------------------------

= 07.12.2023 17:25:29 (UTC +8:00) === ECU-TEST 2023.3.0.141374+8eeee403f0b5 141374+8eeee403f0b5 (2023/09/19 16:45:04) (64bit) ===
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]

License: ECU-TEST
         - License options:
             + Diagnostics add-on
             + Trace Analysis
         - valid up to version: 2023.4
         - valid until: 31-dec-2023
         - licensed for: TURING
         - Server: Eric


2023-12-07 17:25:29.045 6940 ManagedWorker-2*PE.Run() DEBUG_EXC_PRINT:
                        Traceback (most recent call last):
                          File "tts\core\package\dataStructures\SpecialStructures.py", line 145, in __call__
                          File "<string>", line 6, in func
                          File ".\Lib\site-packages\openpyxl\workbook\workbook.py", line 287, in __getitem__
                        KeyError: 'Worksheet sheet1 does not exist.'
                        
                        The above exception was the direct cause of the following exception:
                        
                        Traceback (most recent call last):
                          File "tts\core\expressions\BaseExpressionChildren.py", line 1366, in Evaluate
                          File "tts\core\package\dataStructures\SpecialStructures.py", line 148, in __call__
                        RuntimeError: Runtime error in function variable, line 6: KeyError, 'Worksheet sheet1 does not exist.'.
                        
                        During handling of the above exception, another exception occurred:
                        
                        Traceback (most recent call last):
                          File "tts\testExecution\testSteps\dataoperations\calculationNG\TsCalculationExec.py", line 147, in Call
                          File "tts\core\expressions\BaseExpressionChildren.py", line 1370, in Evaluate
                        tt._Exceptions_.TTError: An error occurred when calling "Unnamed('C')": Runtime error in function variable, line 6: KeyError, 'Worksheet sheet1 does not exist.'.
                        
                        During handling of the above exception, another exception occurred:
                        
                        Traceback (most recent call last):
                          File "tts\testExecution\engine\TestEngine.py", line 1002, in ExecuteTestStep
                          File "tts\testExecution\testSteps\dataoperations\calculationNG\TsCalculationExec.py", line 208, in Run
                          File "tts\testExecution\testSteps\dataoperations\calculationNG\TsCalculationExec.py", line 151, in Call
                        tts.testExecution.testSteps.dataoperations.calculationNG.TsCalculationExec.UserCodeException: An error occurred when calling "Unnamed('C')": Runtime error in function variable, line 6: KeyError, 'Worksheet sheet1 does not exist.'.
