

-------------------------------------------------------------------------
Systeminfo:
CPU:               AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
Number of CPUs:    16
RAM:               15.2GB
Diskinfo:          47.2GB/475.7GB
Operating system:  Windows-10-10.0.19045
Long path support: False
-------------------------------------------------------------------------

= 05.12.2023 13:47:31 (UTC +8:00) === ECU-TEST 2023.3.0.141374+8eeee403f0b5 141374+8eeee403f0b5 (2023/09/19 16:45:04) (64bit) ===
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]

License: ECU-TEST
         - License options:
             + Diagnostics add-on
             + Trace Analysis
         - valid up to version: 2023.4
         - valid until: 31-dec-2023
         - licensed for: TURING
         - Server: Eric


2023-12-05 13:47:31.602 9864 ManagedWorker-1*PE.Run() DEBUG_EXC_PRINT:
                        Traceback (most recent call last):
                          File "tts\core\toolingFramework\testbenchConfig\Testbench.py", line 1128, in Port
                          File "tts\core\toolingFramework\toolAccess\Binding.py", line 452, in GetPort
                          File "tts\core\toolingFramework\toolAccess\BindingBase.py", line 112, in GetPortBinding
                        tts.core.toolingFramework.toolAccess.Exceptions.IdException: Invalid port-ID: BUS01
                        
                        During handling of the above exception, another exception occurred:
                        
                        Traceback (most recent call last):
                          File "tts\core\package\engine\ExecutionMappingSpaceManager.py", line 534, in __CallRegisterXaObjects
                          File "tts\testModule\bus\mapping\XABusSignalVariableExec.py", line 24, in PrepareWrite
                          File "tts\core\mapping\xa\XAVariableExec.py", line 91, in GetPort
                          File "tts\core\toolingFramework\testbenchConfig\Testbench.py", line 1133, in Port
                        tts.core.toolingFramework.testbenchConfig.Testbench.TestbenchError: Invalid port id: BUS01
